---
# tasks file for roles/rss-bridge

    
        
  - name: "Mount {{ nfs_server }}:{{server_config_path}} to {{configs_mount_path}}"
    mount:
        src: "{{nfs_server}}:{{server_config_path}}"
        path: "{{configs_mount_path}}"
        state: mounted
        fstype: nfs
        
  - name: "Ensure {{configs_mount_path}}{{role_config_suffix}} exists, create it if it doesn't"
    ansible.builtin.file:
        mode: 0775
        state: directory
        path: "{{configs_mount_path}}{{role_config_suffix}}"
        
  - name: "Create whitelist.txt in mountpoint from template"
    template: 
        src: whitelist.txt.j2
        dest: "{{ configs_mount_path }}{{ role_config_suffix }}app/whitelist.txt"
    notify: Restart rss-bridge container

           
  - name: "Deploy rss-bridge container"
    docker_container:
        name: rss-bridge
        hostname: rss-bridge
        image: rssbridge/rss-bridge
        restart_policy: unless-stopped
        state: started
        ports: "{{ role_ui_port }}:80"
        mounts:
          - source: "{{ configs_mount_path }}{{role_config_suffix}}"
            target: /config
            read_only: no
            type: bind
          - source: "{{ configs_mount_path }}{{role_config_suffix}}app/bridges"
            target: /app/bridges
            read_only: no
            type: bind
          - source: "{{ configs_mount_path }}{{role_config_suffix}}app/whitelist.txt"
            target: /app/whitelist.txt
            read_only: no
            type: bind
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "100"
        comparisons:        
            env: strict


  - name: "Success Notification"
    debug:
        msg: "rss-bridge is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
