---
# tasks file for roles/grafana

  - name: "Install python-pip, virtualenv if they aren't already"
    apt: 
        name:
            - python-pip
            - virtualenv
            - python-setuptools
            - nfs-common
        state: present
        update_cache: yes

  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent
    
  - name: "Install Python docker pkg via pip if not already installed"
    pip:
        name: 
           - docker
        state: present

  - name: "Deploy grafana container"
    docker_container:
        name: grafana
        image: grafana/grafana
        restart_policy: always
        state: started
        ports: 3000:3000
        env:
            GF_INTSTALL_PLUGINS: "{{ grafana_plugins }}"
        comparisons:        
            env: strict
