---
# tasks file for roles/grafana

  - name: "Install python-pip, virtualenv if they aren't already"
    apt: 
        name:
            - python-pip
            - virtualenv
            - python-setuptools
            - nfs-common
        state: present
        update_cache: yes

  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent
    
  - name: "Install Python docker pkg via pip if not already installed"
    pip:
        name: 
           - docker
        state: present

  - name: "Creates named docker volume at {{ grafana_mount_path }}"
    docker_volume:
        volume_name: grafana_persist
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ grafana_nfs_path }}"
            



  - name: "Deploy grafana container"
    docker_container:
        name: grafana
        image: grafana/grafana
        restart_policy: always
        network_mode: host
        state: started
        ports: 3000:3000
        env:
            GF_INSTALL_PLUGINS: "{{ grafana_plugins }}"         
        mounts:
          - source: grafana_persist
            target: "/var/lib/grafana"
            read_only: no
            type: volume     
        comparisons:        
            env: strict
