---
# tasks file for roles/statping
         

  - name: "Deploy statping container"
    docker_container:
        name: statping
        image: statping/statping
        state: started
        restart_policy: always
        ports: 8080:8080
        mounts:
          - source: "{{ statping_data_path }}"
            target: "/app"
            read_only: no
            type: bind
        comparisons:        
            env: strict
