---

  - hosts: 20-size.local
    remote_user: ansible
    become: yes


    pre_tasks:
       
       - name: "Install pip, setuptools, virtualenv if not already"
         apt: 
            name:
                - python3-pip
                - python-setuptools
                - virtualenv
            state: present
            update_cache: yes
    
       - name: "Install pyOpenSSL if not already"
         pip:
            name:
               - cryptography 
               - docker
               - pyOpenSSL  # required for OpenSSL cert creation
            state: present



    roles:
      - role: common
        tags:
          - common
      - role: cloudalchemy.node-exporter
        tags:
          - node-exporter
      - role: geerlingguy.nfs
      # `insecure` option required for NFS to be mountable via MacOS' finder
        nfs_exports: 
          [
          "/snoqualmie/media 10.0.1.0/24(rw,sync,no_root_squash,insecure)", 
          "/seatac/plex 10.0.1.0/24(rw,sync,no_root_squash,insecure)"
          ]
        tags:
          - nfs
      - role: docker
        tags:
          - docker
      - role: zcube-cadvisor
        tags:
          - cadvisor


