---

  - hosts: 20-size.local
    remote_user: ansible
    become: yes

#    pre_tasks:
#       
#       - name: "Install pip, setuptools, virtualenv if not already"
#         apt: 
#            name:
#                - python-pip
#                - python-setuptools
#                - virtualenv
#            state: present
#            update_cache: yes
#    
#       - name: "Install pyOpenSSL if not already"
#         pip:
#            name:
#               - cryptography 
#               - pyOpenSSL  # required for OpenSSL cert creation
#            state: present

       
    roles:
      - role: common
        tags:
          - common
      - role: cloudalchemy.node-exporter
        tags:
          - node-exporter
#      - role: docker
#        tags:
#          - docker


