---

  - hosts: 20-size.local
    remote_user: ansible
    become: yes


    pre_tasks:
       
       - name: "Install pip, setuptools, virtualenv if not already"
         apt: 
            name:
                - python3-pip
                - python-setuptools
                - virtualenv
            state: present
            update_cache: yes
    
       - name: "Install pyOpenSSL if not already"
         pip:
            name:
               - cryptography 
               - docker
               - pyOpenSSL  # required for OpenSSL cert creation
            state: present
#       - name: "Create Media ZFS filesystem on Snoqualmie zpool"
#         tags: 
#           - zfs
#           - snoqualmie
#         community.general.zfs: 
#           name: snoqualmie/media
#           state: present
#       - name: "Create Plex ZFS filesystem on Seatac zpool"
#         tags: 
#           - zfs
#           - seatac
#         community.general.zfs: 
#           name: seatac/plex
#           state: present
#       - name: "Create backups ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/backups
#           state: present
#       - name: "Create homebridge ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/homebridge
#           state: present
#       - name: "Create homebridge ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/homebridge
#           state: present
#       - name: "Create grafana ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/grafana
#           state: present
#       - name: "Create varken ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/varken
#           state: present
#       - name: "Create prometheus ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/prometheus
#           state: present
#       - name: "Create influxDB ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/influxDB
#           state: present
#       - name: "Create znbget ZFS filesystem on Whidbey zpool"
#         tags: 
#           - zfs
#           - whidbey
#         community.general.zfs: 
#           name: whidbey/nzbget
#           state: present        

       - name: Creating directories for consumption by NFS clients
         ansible.builtin.file:
            state: directory
            dest: "{{ item }}"
         loop:
            # Prometheus
            - /whidbey/prometheus/database/
            # Grafana
            - /whidbey/grafana/data
            - /whidbey/grafana/config
            # InfluxDB
            - /whidbey/influxDB/db
            # NZBGet
            - /whidbey/nzbget/intermediate
            # Varken
            - /whidbey/varken/config           
    roles:
      - role: common
        tags:
          - common
      - role: cloudalchemy.node-exporter
        tags:
          - node-exporter
      - role: geerlingguy.nfs
      # `insecure` option required for NFS to be mountable via MacOS' finder
        nfs_exports: 
          [
          "/snoqualmie/media 10.0.1.0/24(rw,async,no_root_squash,insecure,insecure_locks)", 
          "/seatac/plex 10.0.1.0/24(rw,sync,no_root_squash,insecure,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/backups 10.0.1.0/24(rw,sync,no_root_squash,insecure,crossmnt,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/homebridge 10.0.1.0/24(rw,sync,no_root_squash,insecure,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/grafana 10.0.1.0/24(rw,sync,no_root_squash,insecure,crossmnt,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/varken 10.0.1.0/24(rw,sync,no_root_squash,insecure,crossmnt,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/prometheus 10.0.1.0/24(rw,sync,no_root_squash,insecure,crossmnt,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/influxDB 10.0.1.0/24(rw,sync,no_root_squash,insecure,insecure_locks,anonuid=1024,anongid=100)",
#          "/whidbey/ombi_config 10.0.1.0/24(rw,sync,no_root_squash,insecure,insecure_locks,anonuid=1024,anongid=100)",
          "/whidbey/nzbget 10.0.1.0/24(rw,sync,no_root_squash,insecure,crossmnt,insecure_locks,anonuid=1024,anongid=100)"
          ]
        tags:
          - nfs
      - role: docker
        tags:
          - docker
      - role: zcube-cadvisor
        tags:
          - cadvisor
      - role: plex
        tags:
          - plex
      - role: shinobi
        tags:
          - shinobi        
      - role: tautulli
        tags:
          - tautulli


