---
  - name: Configure NFS Server
    hosts: 20-size.local
    remote_user: ansible
    become: yes
    
    
    tasks: 
      - name: Create folder in /whidbey/configs for each role
        file:
          path: "/whidbey/configs/{{item}}"
          state: directory
          mode: 0775
          owner: ansible
          group: docker
        loop:
          - varken
          - nzbget/intermediate
          - rss-bridge
          - rss-bridge/app/bridges


  - name: Configure Application node 
    hosts: application
    remote_user: ansible
    become: yes
    vars_files:
       - vars/vars.yml
    
    pre_tasks:
       
       - name: "Install pip, setuptools, virtualenv if not already"
         apt: 
            name:
                - python3-docker
                - python-setuptools
                - virtualenv
            state: present
            update_cache: yes
    
       - name: "Install pyOpenSSL if not already"
         pip:
            name:
               - cryptography 
               - pyOpenSSL  # required for OpenSSL cert creation
            state: present
    
           
    roles:
       - role: common
         tags: common
       - role: docker
         tags: docker
#      - role: grafana
#        tags: grafana
       - role: zcube-cadvisor
         tags: cadvisor
#      - role: nzbhydra
#        tags: nzbhydra
       - role: varken
         tags: varken
       - role: nzbget
         tags: nzbget
       - role: radarr
         tags: radarr
       - role: sonarr
         tags: sonarr
       - role: nginx_pm
         tags: nginx_pm
       - role: ombi
         tags: ombi
       - role: cloudalchemy.node-exporter
         tags: node-exporter
       - role: prowlarr
         tags: prowlarr
       - role: fresh-rss
         tags: fresh-rss
       - role: heimdall
         tags: heimdall
       - role: rss-bridge
         tags: rss-bridge
       - role: kavita
         tags: kavita
  
