---
  - name: Configure NFS Server
    hosts: 20-size.local
    remote_user: ansible
    become: yes
    vars_files:
     - vars/vars.yml

    
    
    tasks: 
      - name: "Create folder in {{server_config_path}} for each role"
        file:
          path: "{{server_config_path}}{{item}}"
          state: directory
          mode: 0775
          owner: ansible
          group: users
        loop:
          - nzbget/intermediate
          - rss-bridge
          - rss-bridge/app/bridges
          - transmission/config
        tags: nfs

      - name: "Create folder in {{ server_media_path }} for each media type"
        file:
          path: "{{server_media_path}}{{item}}"
          state: directory
          mode: 0775
          owner: ansible
          group: users
        loop:
          - adult_audio
          - adult_books
          - adult_manga
          - adult_videos
          - anime
          - books
          - comics
          - manga
          - misc
          - movies
          - music
          - nzb_downloads
          - torrents/watch
          - torrents/downloads/complete
          - photos
          - security_cam_recordings
          - series
          - textbooks
          - videos
        tags: nfs
          


  - name: Configure Application node 
    hosts: application
    remote_user: ansible
    become: yes
    vars_files:
       - vars/vars.yml
    
    pre_tasks:
       
       - name: "Install pip, setuptools, virtualenv if not already"
         apt: 
            name:
                - python3-docker
                - python3-pip              
                - python3-venv
                - python3-cryptography
                - libssl-dev
                - libffi-dev
            state: present
            update_cache: yes
    
    roles:
       - role: common
         tags: common
       - role: docker
         tags: docker
#        - role: zcube-cadvisor
#          tags: cadvisor
       - role: nzbget
         tags: nzbget
       - role: transmission
         tags: transmission
       - role: radarr
         tags: radarr
       - role: readarr
         tags: readarr
       - role: sonarr
         tags: sonarr
       - role: lidarr
         tags: lidarr
       - role: nginx_pm
         tags: nginx_pm
       - role: ombi
         tags: ombi
       - role: prowlarr
         tags: prowlarr
#        - role: fresh-rss
#          tags: fresh-rss
#        - role: heimdall
#          tags: heimdall
#        - role: rss-bridge
#          tags: rss-bridge
#        - role: kavita
#          tags: kavita
         
  
