---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgAgmC+ADasWQB7Hu0Q+cexmdCd+vAlX68qjwLDCd1TzHeRSLnKbEgc55Ctb2P5ICvtrleE2NDODBlMwtQigd5/8RczQo16x2N+WASZI5o+vDuS+GXTNfLkrn65VlGVNc5kPs+7vzz41CPw/86DeJG+8MKaO7RLvzKq8tKGV5veBxusyI080V45fyGgtOiCYMYxlKwkUZ5lz/V8an6C5kxPLsG2HKlzPKrLXxDq8O5Y9ie58/ACskTx2mWLaWON9UfTFmHHrmMiWbEfOrcukfbLh9M5btVuQyqCL4pVR/tISOFmg1Z2nFLm481/QhOQQswVpCl0CnK35YPBHZMAgTQpHxXAM3Yr31/MKyI3Jv+69qQ427f1zUij5+DxKOoa61MRlGTnlUAHXmYC6Zdh4zMunIPwI/LDMeNv8Hs1/8uc0mKA4MTNLjxU9X+AzSfU8hKo89VxCV3g23cGP5oaxYPuzuJOf0Mo/H65I+TVrm22MDUMbEbyY/aZA3TA8z2IhN6FYKPRQE4QkFoHEYRcDrBIaI+RC2hd4d7HWM++4tmMTkrMFarU8sIOvrgA1muBRCnM7lzvCnHzCJdCkQDhNfvaqOjTglnrTVecMfBY7YZwg+t5Qey8d3hlHPWTOcrrvqlEXcvEWEBrqfWRM7RGQ+1KaUi0tUGcdWn2D0Aa7LaKvYtpP7fLihAKXvYZZGbz4REezBCymIh8NRb0GNevtLIieOB8oCCa43YpvM6iExmhwurh26YdFG71URI1a
  template:
    metadata:
      name: traefik-basic-auth
      namespace: kube-system
