---
# tasks file for roles/zcube-cadvisor

  - name: Append details to /boot/cmdline.txt
    linelinfile:
        create: yes
        state: present
        path: /boot/cmdline.txt
        line: " cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"

  - name: Append to /etc/docker/daemon.json
    lineinfile:
        create: yes
        state: present
        path: /etc/docker/daemon.json
        line: '{ "exec-opts": ["native.cgroupdriver=systemd"] }'



  - name: "Deploy cAdvisor container"
    docker_container:
        name: cAdvisor
        image: zcube/cadvisor
        restart_policy: always
        state: started
        ports: 8000:8080
        volumes: 
            - /:/rootfs:ro
            - /var/run:/var/run:ro 
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro 
        comparisons:        
            env: strict