---
galaxy_info:
  author: Ansible k3s role
  description: Installs and configures k3s (lightweight Kubernetes)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - k3s
    - kubernetes
    - container
    - arm

dependencies:
  - role: common
