---
# tasks file for roles/k8s

- name: Install python3, pip, & kubernetes python libraries
  ansible.builtin.apt: 
    name: 
      - python3=3.11.2-1
      - python3-pip  
      - python3-kubernetes
    state: present

- name: Add sysctl rules to enable iptables visibility to bridged network traffic
  ansible.builtin.lineinfile:
      path: /etc/sysctl.d/k8s.conf
      search_string: "{{ item|string }}"
      line: "{{ item|string }}"
      state: present
      create: true
      backup: true
      insertafter: EOF
      owner: root
      group: root
  loop: "{{ k8s_iptables_add }}" 
  notify: "reload sysctl"


- name: Create /etc/containerd if it doesn't exist
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root


- name: Drop in containerd.toml config file from template
  template:
    backup: true
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
  notify: "restart continerd"


- name: Add packages.cloud.google.com atp key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Set up the stable xenial repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
      
- name: Install k8s packages
  ansible.builtin.apt:
    name: "{{ item|string }}"
    state: present
    update_cache: yes
  loop: "{{ k8s_packages }}"
  register: needs_init

- name: Mark k8s packages hold in dpkg and therefore apt
  ansible.builtin.dpkg_selections:
    name: "{{ item| string }}"
    selection: hold
  loop: "{{ k8s_packages }}"


- name: Chill for a min
  ansible.builtin.pause:
    prompt: "[Press [Return]: About to head into cluster init tasks"

- name: Detour to Cluster Setup when cluster has not yet been set up.
  include_tasks: cluster_init.yml
  when: (inventory_hostname in groups['manager'])
    
  
  
