---
# tasks file for roles/heimdall

    
#  - name: "Ensures /container_data/sonarr_config exists, creates it if not"
#    ansible.builtin.file:
#        group: docker
#        mode: 0755
#        owner: ansible
#        state: directory
#        path: "{{ role_local_config_path }}"

#  - name: "Ensures {{ media_mount_path }} exists, creates it if not"
#    ansible.builtin.file:
#        group: docker
#        mode: 0755
#        owner: ansible
#        state: directory
#        path: "{{ media_mount_path }}"
        
  - name: "Mount {{ nfs_server }}:{{server_config_path}} to {{configs_mount_path}}"
    mount:
        src: "{{nfs_server}}:{{server_config_path}}"
        path: "{{configs_mount_path}}"
        state: mounted
        fstype: nfs
        
  - name: "Ensure {{configs_mount_path}}{{role_config_suffix}} exists, create it if it doesn't"
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{configs_mount_path}}{{role_config_suffix}}"

           
  - name: "Deploy Heimdall container"
    docker_container:
        name: heimdall
        hostname: heimdall
        image: linuxserver/heimdall
        restart_policy: unless-stopped
        state: started
        ports: "{{ role_ui_port }}:80"
        mounts:
          - source: "{{ configs_mount_path }}{{role_config_suffix}}"
            target: /config
            read_only: no
            type: bind
        env:
            TZ: "America/Los_Angeles"
            PUID: "1001"
            PGID: "100"
        comparisons:        
            env: strict


  - name: "Success Notification"
    debug:
        msg: "Heimdall is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
