---
# tasks file for roles/radarr

    


  - name: "Creates named docker volume media"
    docker_volume:
        volume_name: media
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ media_nfs_path }}"

  - name: "Creates named docker volume radarr_config"
    docker_volume:     
        volume_name: radarr_config
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ radarr_config_nfs_path }}"

           
  - name: "Deploy Radarr container"
    docker_container:
        name: radarr
        hostname: radarr
        image: linuxserver/radarr
        restart_policy: always
        state: started
        ports: 7878:7878
        mounts:
          - source: radarr_config
            target: /config
            read_only: no
            type: volume
          - source: media
            target: /media
            read_only: no
            type: volume
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "995"
        comparisons:        
            env: strict
