---
# tasks file for roles/fresh-rss

    
        
  - name: "Mount {{ nfs_server }}:{{server_config_path}} to {{configs_mount_path}}"
    mount:
        src: "{{nfs_server}}:{{server_config_path}}"
        path: "{{configs_mount_path}}"
        state: mounted
        fstype: nfs
        
  - name: "Ensure {{configs_mount_path}}{{role_config_suffix}} exists, create it if it doesn't"
    ansible.builtin.file:
        mode: 0775
        state: directory
        path: "{{configs_mount_path}}{{role_config_suffix}}"

           
  - name: "Deploy Fresh-RSS container"
    docker_container:
        name: freshrss
        hostname: freshrss
        image: linuxserver/freshrss
        restart_policy: unless-stopped
        state: started
        ports: "{{ role_ui_port }}:80"
        mounts:
          - source: "{{ configs_mount_path }}{{role_config_suffix}}"
            target: /config
            read_only: no
            type: bind
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "100"
        comparisons:        
            env: strict
            
  - name: "Pull Extensions to {{ configs_mount_path }}{{role_config_suffix}}{{ extensions_subdir }}"
    ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ configs_mount_path }}{{role_config_suffix}}{{ extensions_subdir }}{{ item.name }}"
    loop:
      - { name: 'AutoRefresh', repo: 'https://github.com/Eisa01/FreshRSS---Auto-Refresh-Extension'}
        
        
#   - name: add several users
#     user:
#      name: "{{ item.name }}"
#      state: present
#      groups: "{{ item.groups }}"
#     loop:
#      - { name: 'testuser1', groups: 'wheel' }
#      - { name: 'testuser2', groups: 'root' }



  - name: "Success Notification"
    debug:
        msg: "Fresh-rss is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
