---
# tasks file for homebridge
   
  - name: "Create mountpoint"
    file: 
        path: "{{ homebridge_mount_path }}"
        state: directory
        mode: 0777
        owner: root
        group: users
        

  - name: "Mount nfs drive for Homebridge filesystem"
    mount: 
        path: "{{ homebridge_mount_path }}"
        src: "{{ nfs_server }}:{{ homebridge_nfs_path }}"
        state: mounted
        fstype: nfs
        
  - name: "Create config.json in mountpoint from template"
    template: 
        src: homebridge.config.json.j2
        dest: "{{ homebridge_mount_path }}/config.json"
    notify: Restart homebridge container

  - name: "Create startup.sh in mountpoint from template"
    template: 
        src: homebridge.startup.sh.j2
        dest: "{{ homebridge_mount_path }}/startup.sh"
    notify: Restart homebridge container
    
        
  - name: "Deploy Homebridge container"
    docker_container:
        name: homebridge
        image: oznu/homebridge:latest
        restart_policy: always
        state: started
        network_mode: host
        env:
        # might need to replace PGIO and PUID with user parameter
            PGID: "995"
            PUID: "1002"
            HOMEBRIDGE_CONFIG_UI: "1"
            HOMEBRIDGE_CONFIG_UI_PORT: "{{ homebridge_ui_port }}"
        volumes:
            - "{{ homebridge_mount_path }}:/homebridge"
        comparisons:
            '*': ignore
            env: strict
            
  - name: "Homebridge Success Notification"
    debug:
        msg: "Homebridge is now accessible at http://{{ ansible_hostname }}.local:{{ homebridge_ui_port }}"
        