---
# tasks file for homebridge
   
  - name: "Create mountpoint"
    file: 
        path: "{{ configs_mount_path }}"
        state: directory
        mode: 0777
        owner: root
        group: users
        

  - name: "Mount nfs for configs filesystem"
    mount: 
        path: "{{ configs_mount_path }}"
        src: "{{ nfs_server }}:{{ server_config_path }}"
        state: mounted
        fstype: nfs
        
  - name: "Create config.json in mountpoint from template"
    template: 
        src: homebridge_cb.config.json.j2
        dest: "{{ configs_mount_path }}{{ role_subdir }}config.json"
    notify: Restart homebridge container

  - name: "Create startup.sh in mountpoint from template"
    template: 
        src: homebridge.startup.sh.j2
        dest: "{{ configs_mount_path }}{{ role_subdir }}startup.sh"
    notify: Restart homebridge container

       
  - name: "Deploy Homebridge container"
    docker_container:
        name: homebridge
        image: homebridge/homebridge
        restart_policy: always
        state: started
        network_mode: host
        ports: "{{ homebridge_ui_port }}:8080"
        env:
        # might need to replace PGIO and PUID with user parameter
            PGID: "995"
            PUID: "1002"
            HOMEBRIDGE_CONFIG_UI: "1"
            HOMEBRIDGE_CONFIG_UI_PORT: "{{ homebridge_ui_port }}"
        volumes:
          - "{{ configs_mount_path }}{{ role_subdir }}:/homebridge"
        comparisons:
            '*': ignore
            env: strict
            
  - name: "Homebridge Success Notification"
    debug:
        msg: "Homebridge is now accessible at http://{{ ansible_hostname }}.local:{{ homebridge_ui_port }}"
        