apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    name: plex
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: homebridge
  labels:
    name: homebridge
---
apiVersion: v1
kind: Namespace
metadata:
  name: homeautomation
  labels:
    name: homeautomation
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    # Disable validation for cert-manager namespace
    cert-manager.io/disable-validation: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    name: sealed-secrets
