---
# tasks file for roles/varken


  - name: "Install python-pip, virtualenv if they aren't already"
    apt: 
        name:
            - python-pip
            - virtualenv
            - python-setuptools
            - nfs-common
        state: present
        update_cache: yes

  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent
    
  - name: "Install Python docker pkg via pip if not already installed"
    pip:
        name: 
           - docker
        state: present

  - name: "Create mountpoint"
    file: 
        path: "{{ varken_mount_path }}"
        state: directory
        mode: 0777
        owner: root
        group: users
        

  - name: "Mount nfs drive for varken filesystem"
    mount: 
        path: "{{ varken_mount_path }}"
        src: "{{ nfs_server }}:{{ varken_nfs_path }}"
        state: mounted
        fstype: nfs

  - name: "Create varken.ini in mountpoint from template"
    template: 
        src: varken.ini.j2
        dest: "{{ varken_mount_path }}/varken.ini"
    notify: Restart varken container


  - name: "Creates named docker volume for varken persistent data"
    docker_volume:
        volume_name: varken_persist
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ varken_nfs_path }}"
            

            
            
  - name: "Deploy varken container"
    docker_container:
        name: varken
        hostname: varken
        image: boerderij/varken
        restart_policy: always
        state: started
        ports: 9090:9090
        mounts:
          - source: varken_persist
            target: /config
            read_only: no
            type: volume      
        env:
            TZ: "America/Los Angeles"
            
#            PUID: "1002"
#            PGID: "995"
        comparisons:        
            env: strict    