---
# tasks file for roles/varken


  - name: "Install python-pip, virtualenv if they aren't already"
    apt: 
        name:
            - python-pip
            - virtualenv
            - python-setuptools
            - nfs-common
        state: present
        update_cache: yes

  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent
    
  - name: "Install Python docker pkg via pip if not already installed"
    pip:
        name: 
           - docker
        state: present

  - name: "Create mountpoint"
    file: 
        path: "{{ role_mount_path }}"
        state: directory
        mode: 0777
        owner: ansible
        group: docker
        

  - name: "Mount nfs drive for varken filesystem"
    mount: 
        path: "{{ role_mount_path }}"
        src: "{{ nfs_server }}:{{ server_config_path }}{{role_config_suffix}}"
        state: mounted
        fstype: nfs

  - name: "Create varken.ini in mountpoint from template"
    template: 
        src: varken.ini.j2
        dest: "{{ role_mount_path }}/varken.ini"
    notify: Restart varken container       
          
            
  - name: "Deploy varken container"
    docker_container:
        name: varken
        hostname: varken
        image: boerderij/varken
        restart_policy: always
        state: started
        ports: "{{ role_ui_port }}:9090"
        mounts:
          - source: "{{ role_mount_path }}"
            target: /config
            read_only: no
            type: bind      
        env:
            TZ: "America/Los Angeles"
        comparisons:        
            env: strict    
            
            
  - name: "Success Notification"
    debug:
        msg: "Varken is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
