---
# tasks for distributing kubeconfig to users
# Runs only on the k3s server node

- name: Create .kube directory for common users
  ansible.builtin.file:
    path: "{{ '/home/' + item + '/.kube' }}"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0755'
  loop: "{{ common_users }}"

- name: Copy k3s.yaml to user kubeconfig
  ansible.builtin.shell: |
    cp /etc/rancher/k3s/k3s.yaml /home/{{ item }}/.kube/config
    sed -i 's/127.0.0.1/{{ k3s_server_host }}/g' /home/{{ item }}/.kube/config
    chown {{ item }}:{{ item }} /home/{{ item }}/.kube/config
    chmod 600 /home/{{ item }}/.kube/config
  loop: "{{ common_users }}"
  changed_when: true
