---
# tasks file for roles/nzbget

  - name: "Creates named docker volume media"
    docker_volume:
        volume_name: media
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ media_nfs_path }}"


  - name: "Creates named docker volume at {{ nzbget_intermediate }}"
    docker_volume:
        volume_name: nzb_intermediate
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ nzb_intermediate_nfs_path }}"

  - name: "Create {{ nzbget_config_path }} if it does not exist"
    file:
        path: "{{ nzbget_config_path }}"
        state: directory
        mode: '0775'     
    
  - name: "Create nzbget.conf in {{ nzbget_config_path }} from template"
    template: 
        src: nzbget.conf.j2
        dest: "{{ nzbget_config_path }}/nzbget.conf"
    tags: deploy_prom_config       
            
  - name: "Deploy NZBget container"
    docker_container:
        name: nzbget
        hostname: nzbget
        image: linuxserver/nzbget
        restart_policy: always
        state: started
        ports: 6789:6789
        mounts:
          - source: nzbget_intermediate
            target: /intermediate
            read_only: no
            type: volume
          - source: media
            target: /media
            read_only: no
            type: volume
        volumes:
          - "{{ nzbget_config_path }}:/config"
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "995"
        comparisons:        
            env: strict
