---
# tasks file for roles/sonarr

    
  - name: Ensures /container_data/sonarr_config exists, creates it if not
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{ local_config_path }}"
        
# May be able to build a handler that responds if the above is empty and copies,
# rsyncs, or restores from backup. 

  - name: "Creates named docker volume: media"
    docker_volume:
        volume_name: "{{ media_volume_name }}"
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ media_nfs_path }}"

# Creating a named volume would be nice and would make data migration among
# containers easier. Should figured out a shared volume first. 
#  - name: "Creates named docker volume sonarr_config"
#    docker_volume:     
#        volume_name: sonarr_config
#        state: present
#        driver_options: 
##            type: ext4
##           o: "addr={{ nfs_server }},rw"
#            device: "{{ local_config_dir }}"

           
  - name: "Deploy Sonarr container"
    docker_container:
        name: sonarr
        hostname: sonarr
        image: linuxserver/sonarr
        restart_policy: unless-stopped
        state: started
        ports: 8989:8989
        mounts:
          - source: "{{ local_config_path }}"
            target: /config
            read_only: no
            type: bind
          - source: "{{ media_volume_name }}"
            target: /media
            read_only: no
            type: volume
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "995"
        comparisons:        
            env: strict
