---
# tasks file for roles/nzbhydra

  - name: "Create {{ role_local_config_path }} if it does not exist"
    file:
        path: "{{ role_local_config_path }}"
        state: directory
        mode: '0775'     


  - name: "Ensures {{ media_mount_path }} exists, creates it if not"
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{ media_mount_path }}"
        
  - name: "Mount {{ nfs_server }}:{{server_media_path}} to {{media_mount_path}}"
    mount:
        src: "{{nfs_server}}:{{server_media_path}}"
        path: "{{media_mount_path}}"
        state: mounted
        fstype: nfs

     
            
  - name: "Deploy nzbHydra2 container"
    docker_container:
        name: nzbhydra
        hostname: nzbhydra
        image: linuxserver/nzbhydra2
        restart_policy: unless-stopped
        state: started
        ports: "{{ role_ui_port }}:5076"
        mounts:
          - source: "{{ media_mount_path }}"
            target: /media
            read_only: no
            type: bind
        volumes:
          - "{{ role_local_config_path }}:/config"
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "100"
        comparisons:        
            env: strict

  - name: "Success Notification"
    debug:
        msg: "NZBHydra is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
