---
# tasks file for roles/nzbhydra

  - name: "Creates named docker volume media"
    docker_volume:
        volume_name: media
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ media_nfs_path }}"


  - name: "Create {{ hydra_local_config_path }} if it does not exist"
    file:
        path: "{{ hydra_local_config_path }}"
        state: directory
        mode: '0775'     
     
            
  - name: "Deploy nzbHydra2 container"
    docker_container:
        name: nzbhydra
        hostname: nzbhydra
        image: linuxserver/nzbhydra2
        restart_policy: unless-stopped
        state: started
        ports: "{{ nzbhydra_ui_port }}:5076"
        mounts:
          - source: media
            target: /media
            read_only: no
            type: volume
        volumes:
          - "{{ hydra_local_config_path }}:/config"
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "100"
        comparisons:        
            env: strict

  - name: "Success Notification"
    debug:
        msg: "NZBHydra is now accessible at http://{{ ansible_hostname }}.local:{{ nzbhydra_ui_port | string }}"
