---
# tasks file for roles/nzbhydra

  - name: "Creates named docker volume media"
    docker_volume:
        volume_name: media
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ media_nfs_path }}"


  - name: "Create {{ hydra_local_config_path }} if it does not exist"
    file:
        path: "{{ hydra_local_config_path }}"
        state: directory
        mode: '0775'     
    
#  - name: "Create nzbget.conf in {{ nzbget_config_path }} from template"
#    template: 
#        src: nzbget.conf.j2
#        dest: "{{ nzbget_config_path }}/nzbget.conf"
#    tags: deploy_prom_config
#    notify: 
#      - Restart nzbget container       
            
  - name: "Deploy nzbHydra2 container"
    docker_container:
        name: nzbhydra
        hostname: nzbhydra
        image: linuxserver/nzbhydra2
        restart_policy: unless-stopped
        state: started
        ports: 5076:5076
        mounts:
          - source: media
            target: /media
            read_only: no
            type: volume
        volumes:
          - "{{ hydra_local_config_path }}:/config"
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "995"
        comparisons:        
            env: strict
