#!/usr/bin/env python3
"""Marvin Health Prometheus textfile exporter.

Runs marvin_health.py, converts the JSON report to Prometheus exposition format,
and writes it atomically to the node_exporter textfile collector directory.

node_exporter picks it up via --collector.textfile.directory and ships it to
Grafana Cloud (Mimir) via Alloy.

Metrics emitted:
  marvin_http_up{service}              1 if reachable, 0 if down
  marvin_systemd_active{service}       1 if active, 0 if inactive/error
  marvin_ssl_days_remaining{name,host} days until cert expiry (-999 on error)
  marvin_disk_used_percent{name,mount} used% for each local filesystem (0-100)
  marvin_disk_avail_bytes{name,mount}  available bytes for each local filesystem
  marvin_health_last_scrape_timestamp  Unix timestamp of last successful run
"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HEALTH_SCRIPT = Path("/home/openclaw/marvin_health.py")
TEXTFILE_PATH = Path("/var/lib/node_exporter/textfile_collector/marvin_health.prom")


def _escape(v: str) -> str:
    return v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def run_health_check() -> dict:
    result = subprocess.run(
        [sys.executable, str(HEALTH_SCRIPT)],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0:
        raise RuntimeError(f"marvin_health.py failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def write_metrics_atomic(lines: list):
    TEXTFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = TEXTFILE_PATH.with_suffix(".prom.tmp")
    tmp.write_text("\n".join(lines) + "\n")
    tmp.rename(TEXTFILE_PATH)


def main():
    try:
        report = run_health_check()
    except Exception as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)

    out = []
    now_ts = int(datetime.now(timezone.utc).timestamp())

    # ── HTTP reachability ─────────────────────────────────────────────────────
    out.append("# HELP marvin_http_up 1 if the service HTTP endpoint is reachable, 0 if down")
    out.append("# TYPE marvin_http_up gauge")
    for entry in report.get("http", []):
        svc = _escape(entry["name"])
        val = 1 if entry.get("status") == "up" else 0
        out.append(f'marvin_http_up{{service="{svc}"}} {val}')

    # ── systemd service status ────────────────────────────────────────────────
    out.append("")
    out.append("# HELP marvin_systemd_active 1 if the systemd service is active, 0 otherwise")
    out.append("# TYPE marvin_systemd_active gauge")
    for entry in report.get("systemd", []):
        svc = _escape(entry["name"])
        val = 1 if entry.get("status") == "active" else 0
        out.append(f'marvin_systemd_active{{service="{svc}"}} {val}')

    # ── SSL cert expiry ───────────────────────────────────────────────────────
    out.append("")
    out.append("# HELP marvin_ssl_days_remaining Days until TLS certificate expiry (-999 if check failed)")
    out.append("# TYPE marvin_ssl_days_remaining gauge")
    for entry in report.get("ssl", []):
        name = _escape(entry["name"])
        host = _escape(entry.get("host", ""))
        if entry.get("status") == "error":
            days = -999
        else:
            days = entry.get("expires_in_days", -999)
        out.append(f'marvin_ssl_days_remaining{{name="{name}",host="{host}"}} {days}')

    # ── Disk usage (20-size local mounts) ────────────────────────────────────
    out.append("")
    out.append("# HELP marvin_disk_used_percent Percentage of disk space used (0-100)")
    out.append("# TYPE marvin_disk_used_percent gauge")
    out.append("# HELP marvin_disk_avail_bytes Available disk space in bytes")
    out.append("# TYPE marvin_disk_avail_bytes gauge")
    for entry in report.get("disk", []):
        name  = _escape(entry["name"])
        mount = _escape(entry.get("mount", ""))
        if entry.get("status") != "error":
            out.append(f'marvin_disk_used_percent{{name="{name}",mount="{mount}"}} {entry.get("used_pct", -1)}')
            out.append(f'marvin_disk_avail_bytes{{name="{name}",mount="{mount}"}} {entry.get("avail_bytes", -1)}')

    # ── scrape timestamp ──────────────────────────────────────────────────────
    out.append("")
    out.append("# HELP marvin_health_last_scrape_timestamp Unix timestamp of last successful health check run")
    out.append("# TYPE marvin_health_last_scrape_timestamp gauge")
    out.append(f"marvin_health_last_scrape_timestamp {now_ts}")

    out.append("")
    out.append(f"# generated by marvin-health-exporter at {datetime.now(timezone.utc).isoformat()}")

    write_metrics_atomic(out)

    http_down = [e["name"] for e in report.get("http", []) if e.get("status") != "up"]
    systemd_down = [e["name"] for e in report.get("systemd", []) if e.get("status") != "active"]
    ssl_warn = [e["name"] for e in report.get("ssl", []) if e.get("status") not in ("ok", "error")]

    print(
        f"Wrote {TEXTFILE_PATH} — "
        f"{len(report.get('http', []))} HTTP, "
        f"{len(report.get('systemd', []))} systemd, "
        f"{len(report.get('ssl', []))} SSL checks"
    )
    if http_down:
        print(f"  DOWN (http): {', '.join(http_down)}")
    if systemd_down:
        print(f"  DOWN (systemd): {', '.join(systemd_down)}")
    if ssl_warn:
        print(f"  SSL warn: {', '.join(ssl_warn)}")


if __name__ == "__main__":
    main()
