---
# handlers file for roles/k8s


- name: "reload sysctl"
  ansible.builtin.command:
      cmd: sysctl --system


- name: "restart continerd"
  ansible.builtin.service:
      enabled: true
      name: containerd
      state: restarted
