---
# tasks file for roles/prometheus---
 
   
  - name: "Create `/container_data/prometheus` if it does not exist"
    file:
        path: "{{ prometheus_config_path }}"
        state: directory
        mode: '0775'
        
  - name: "Create `/container_data/promtetheus/prometheus.yml` from template"
    template: 
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_path }}/prometheus.yml"
    tags: deploy_prom_config
    notify: Restart prometheus container


  - name: "Creates named docker volume prometheus_persist"
    docker_volume:
        volume_name: prometheus_persist
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ prometheus_nfs_path }}"
            

            
            
  - name: "Deploy prometheus container"
    docker_container:
        name: prometheus
        hostname: prometheus
        image: prom/prometheus
        restart_policy: always
        network_mode: host
        state: started
        ports: 9090:9090
        volumes:
          - "{{ prometheus_config_path }}:/etc/prometheus"
        mounts:
          - source: prometheus_persist
            target: /prometheus
            read_only: no
            type: volume      
        env:
          PUID: "1002"
          PGID: "995"
        command: '"--storage.tsdb.no-lockfile" "--config.file=/etc/prometheus/prometheus.yml" "--storage.tsdb.path=/prometheus" "--web.console.libraries=/usr/share/prometheus/console_libraries" "--web.console.templates=/usr/share/prometheus/consoles"'
        comparisons:        
            env: strict