---
# tasks file for roles/prometheus---

  - name: "Install python-pip, virtualenv if they aren't already"
    apt: 
        name:
            - python-pip
            - virtualenv
            - python-setuptools
            - nfs-common
        state: present
        update_cache: yes

  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent
    
  - name: "Install Python docker pkg via pip if not already installed"
    pip:
        name: 
           - docker
        state: present
    
   
  - name: "Create {{ prometheus_config_path }} if it does not exist"
    file:
        path: "{{ prometheus_config_path }}"
        state: directory
        mode: '0775'
        
  - name: "Create prometheus.yml in {{ prometheus_config_path }} from template"
    template: 
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_path }}/prometheus.yml"
        

## For Synology-hosted NFS volume, the squash setting required "Map all users to admin"
## Admittedly, I don't really understand this. 

  - name: "Creates named docker volume at {{ prometheus_mount_path }}"
    docker_volume:
        volume_name: prometheus_persist
        state: present
        driver_options: 
            type: nfs
            o: "addr={{ nfs_server }},rw"
            device: ":{{ prometheus_nfs_path }}"
            

            
            
  - name: "Deploy prometheus container"
    docker_container:
        name: prometheus
        hostname: prometheus
        image: prom/prometheus
        restart_policy: always
        network_mode: host
        state: started
        ports: 9090:9090
        volumes:
          - "{{ prometheus_config_path }}:/etc/prometheus"
        mounts:
          - source: prometheus_persist
            target: /prometheus
            read_only: no
            type: volume      
        env:
          PUID: "1002"
          PGID: "995"
        comparisons:        
            env: strict