---
# tasks file for roles/prometheus---
 
   
  - name: "Create {{ role_local_config_path }} if it does not exist"
    file:
        path: "{{ role_local_config_path }}"
        state: directory
        mode: '0775'
        
  - name: "Create {{ role_local_config_path }}/prometheus.yml` from template"
    template: 
        src: prometheus.yml.j2
        dest: "{{ role_local_config_path }}/prometheus.yml"
    tags: deploy_prom_config
    notify: Restart prometheus container

  - name: "Create a new ext4 primary partition on /dev/sda"
    community.general.parted:
        device: /dev/sda
        number: 1
        name: tsdb
        label: gpt
        state: present
        fs_type: ext4
            
  - name: Create a ext2 filesystem on /dev/sda1
    community.general.filesystem:
        fstype: ext4
        dev: /dev/sda1

  - name: "Create mountpoint for TSDB"
    ansible.builtin.file:
        path: /mnt/tsdb
        state: directory
        mode: '0777'

  - name: "Mount /dev/sda1 to /mnt/tsdb"
    ansible.posix.mount: 
        path: /mnt/tsdb
        src: /dev/sda1
        fstype: ext4
        state: mounted

#  - name: "Ensures {{ configs_mount_path }} exists, creates it if not"
#    ansible.builtin.file:
#        group: docker
#        mode: 0755
#        owner: ansible
#        state: directory
#        path: "{{ configs_mount_path }}"
#        
#  - name: "Mount {{ nfs_server }}:{{server_config_path}} to {{configs_mount_path}}"
#    mount:
#        src: "{{nfs_server}}:{{server_config_path}}"
#        path: "{{ configs_mount_path }}"
#        state: unmounted
#        fstype: nfs          

  - name: "Ensures /mnt/tsdb/prometheus exists, creates it if not"
    ansible.builtin.file:
        group: users
        mode: 0777
        owner: ansible
        state: directory
        path: /mnt/tsdb/prometheus

#  - name: "Create `{{ configs_mount_path }}{{ server_config_suffix }}` if it does not exist"
#    file:
#        path: "{{ configs_mount_path }}{{ server_config_suffix }}"
#        state: directory
#        owner: ansible
#        group: users
#        mode: '0777'
            
            
  - name: "Deploy prometheus container"
    docker_container:
        name: prometheus
        hostname: prometheus
        image: prom/prometheus
        restart_policy: always
        state: started
        ports: "{{ role_ui_port }}:9090"
        volumes:
          - "{{ role_local_config_path }}:/etc/prometheus"
          - "/mnt/tsdb/prometheus:/prometheus"
#       mounts:
#         - source: /mnt/tsdb/prometheus            
#           target: /prometheus
#           read_only: no
#           type: bind
        env:
          PUID: "1002"
          PGID: "100"
#       command: '"--storage.tsdb.no-lockfile" "--config.file=/etc/prometheus/prometheus.yml" "--storage.tsdb.path=/prometheus" "--web.console.libraries=/usr/share/prometheus/console_libraries" "--web.console.templates=/usr/share/prometheus/consoles"'
        command: '"--config.file=/etc/prometheus/prometheus.yml" "--storage.tsdb.path=/prometheus" "--web.console.libraries=/usr/share/prometheus/console_libraries" "--web.console.templates=/usr/share/prometheus/consoles"'
        comparisons:        
            env: strict
            
  - name: "Success Notification"
    debug:
        msg: "Prometheus is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
