---
# tasks file for common


- import_tasks: user_setup.yml

- name: Install docker prerequisites and iptables-persistent
  apt:
      name: 
          - tar
          - unzip
          - zsh
          - nfs-common
          - avahi-daemon
      state: present
      update_cache: yes


- name: "Include Raspbian (32-bit) libseccomp2 workaround if Raspbian 32-bit installed."
  include_tasks: raspbian_32_focal_alpine3.13.yml
  when: 
    - ansible_facts['lsb']['id'] == "Raspbian" 
    - ansible_facts['lsb']['codename'] == "buster" 
  
- name: Configure Ubuntu cGroups Support on nodes in 'kube' group
  include_tasks: ubuntu_cGroups.yml  
  when: inventory_hostname in groups["kube"]
    

# - import_tasks: update_hostname.yml

