---

#   - name: "Modify /boot/firmware/cmdline.txt to enable cGroup support if not already enabled"
#     ansible.builtin.lineinfile:
#       path: /boot/firmware/cmdline.txt
#       regexp: '(.*) ((cgroup_enable=cpuset|cgroup_enable=memory|cgroup_memory=1|swapaccount=1)( {0,}|\n)){4}(.*)'
#       line: '$1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1 $5'
#       state: present
#       backrefs: true
#       backup: true
#       owner: root
#       group: root
#       mode: '0755'
    
- set_fact:  
    cmdline_txt_path: /boot/firmware/cmdline.txt

# - name: "Add 'systemd.unified_cgroup_hierarchy=0' to GRUB Commandline"
#   ansible.builtin.lineinfile:
#     path: /etc/default/grub.d/50-cloudimg-settings.cfg
#     backup: true
#     backrefs: true
#     regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)(.*)'
#     state: present
#     line: \1 systemd.unified_cgroup_hierarchy=0\2


- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: cpuset
    update: false
    
- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: memory
    update: false

- include_tasks: cmdline.yml
  vars:
    key: cgroup_memory
    value: 1
    update: true            
    
- include_tasks: cmdline.yml
  vars:
    key: swapaccount
    value: 1
    update: true
    
    