---
# tasks file for roles/ombi

  - name: Ensures /container_data/ombi_config exists, creates it if not
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{ role_local_config_path }}"


       
  - name: "Deploy Ombi container"
    docker_container:
        name: ombi
        hostname: ombi
        image: linuxserver/ombi
        restart_policy: unless-stopped
        state: started
        ports: "{{ role_ui_port }}:3579"
        mounts:
          - source: "{{ role_local_config_path }}"
            target: /config
            read_only: no
            type: bind
        env:
          TZ: "America/Los_Angeles"
          PUID: "1002"
          PGID: "100"
        comparisons:        
            env: strict

  - name: "Success Notification"
    debug:
        msg: "Ombi is now accessible at http://{{ ansible_hostname }}.local:{{ role_ui_port | string }}"
