
---
- name: Remove conflicting container runtimes or packages
  apt: 
    name: 
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - runc
    state: absent
    update_cache: yes

- name: Install additional networking modules on Ubuntu on rpi
  apt: 
    name: 
      - linux-modules-extra-raspi
    state: present
    update_cache: yes
  when: ansible_lsb.id == "Ubuntu" and  ansible_machine == "aarch64"

- name: Install cacertificate and curl if not installed
  apt: 
    name: 
      - ca-certificates
      - curl
    state: present
    update_cache: yes


- name: Install docker on docker group
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes


- name: Create /etc/docker/daemon.json from template
  template: 
      src: daemon.json.j2
      dest: "/etc/docker/daemon.json"
  notify: Restart docker service
  when: inventory_hostname in groups['kube']

- name: Backup existing docker.service to docker.service.bak
  copy:
      src: "/lib/systemd/system/docker.service"
      remote_src: yes
      dest: "/lib/systemd/system/docker.service.{{ ansible_date_time['iso8601'] }}.bak"
  when: ansible_lsb.id == "Raspbian" or
        ansible_nodename == "20-size"

- name: Drop docker.service into /lib/systemd/system/
  template: 
      src: docker.service.j2
      dest: "/lib/systemd/system/docker.service"
  notify: Restart docker service
  when: ansible_lsb.id == "Raspbian" or
        ansible_nodename == "20-size"

- name: Start docker service, if not started
  ansible.builtin.service:
    name: docker
    state: started
