---
# tasks file for docker role

- name: Install docker prerequisites and iptables-persistent
  apt:
      name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - iptables-persistent
      state: present
      update_cache: yes
  when: (ansible_facts['lsb']['id'] == "Raspbian") or
        (ansible_facts['lsb']['id'] == "Debian" and ansible_facts['machine'] == "aarch64") or
        (ansible_facts['nodename'] == "20-size")


- name: Add Docker's official GPG key
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: 'https://download.docker.com/linux/raspbian/gpg'
    state: present

     
- name: ARM tasks
  include_tasks: setup-arm.yml
  when: ansible_machine is match("aarch64") 
  # details on above can be found in [Testing Strings](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#testing-strings)

- include_tasks: setup-ubuntu.yml
  when: ansible_lsb.id == "Ubuntu" 
    
- include_tasks: docker-ce_setup.yml
  when: inventory_hostname in groups ["docker"]

# - include_tasks: docker.io.yml
#   when: inventory_hostname in groups["kube"]
#    ansible_nodename == "kube03" or... into a list
