---
# tasks file for docker role - ARM specific tasks


  - name: "Remove python-configparser due to incompatibilities with ARM"
    apt:
        name: python-configparser
        state: absent

# armhf likely Raspberry Pi running Raspbian 

#   - name: Add Docker GPG apt key
#     apt_key:
#       url: https://download.docker.com/linux/raspbian/gpg
#       keyring: /etc/apt/keyrings/docker.asc
#       state: present

  - name: get apt key 
    get_url:
      url: https://download.docker.com/linux/{{ ansible_lsb.id | lower() }}/gpg
      dest: /etc/apt/keyrings.docker.gpg

  - name: Set up Docker stable repository
    apt_repository:
      repo: deb https://download.docker.com/linux/{{ ansible_lsb.id | lower() }} {{ ansible_lsb.codename }} stable
      state: present