---
# tasks file for roles/traefik

  - name: Ensures /container_data/traefik_config exists, creates it if not
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{ local_config_path }}"



  - name: "Create traefik.yanl in {{ local_config_path }} from template"      
    template: 
        src: traefik.yaml.j2
        dest: "{{ local_config_path }}/traefik.yaml"
#    notify: Restart traefik container


#  - name: Create traefik Docker swarm service
#    community.docker.docker_swarm_service:
#        name: traefik
#        image: 
#        networks: 
#          - "traefik_private"
#        mounts:
#          - source: "{{ local_config_path }}"
#            target: /etc/traefik/
#            read_only: no
#            type: bind
#          - source: /var/run/docker.sock
#            target: /var/run/docker.sock
#            read_only: no
#            type: bind
  
  - name: Create Docker overlay network traefik_private
    community.docker.docker_network:
        name: traefik_private
        driver: overlay
        state: present
        internal: no


#  - name: Create Docker overlay network traefik_private
#    community.docker.docker_network:
#        name: web
#        driver: overlay
#        state: present
#        internal: no


#  - name: "Deploy traefik container as a swarm service"
  - name: "Deploy traefik container as a swarm service"
    tags: swarm    
    community.docker.docker_swarm_service:
        name: traefik
#        hostname: traefik
        image: traefik
        restart_config: 
            condition: on-failure
            delay: 10m
            max_attempts: 5
        state: present
#        network_mode: default
        networks: 
          - traefik_private
        publish: 
         - target_port: 8080
           published_port: "{{ traefik_ui_port }}"
#           mode: host
         - target_port:  80
           published_port: 80
#            mode: host
         - target_port: 443
           published_port: 443
#            mode: host
        mounts:
          - source: "{{ local_config_path }}"
            target: /etc/traefik/
            readonly: no
            type: bind
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            readonly: no
            type: bind
        env:
          TZ: "America/Los_Angeles"
          PUID: "1001"
          PGID: "997"
        labels:
          # These
#          traefik.docker.network: "traefik_private"
          traefik.enable: "true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
          traefik.http.routers.api.entrypoints: "web"
          traefik.http.routers.api.rule: "Host(`traefik.alvani.me`)" # <== Setting the domain for the dashboard
          traefik.http.routers.api.service: "api@internal" # <== Enabling the api to be a service to access
          traefik.http.services.api.loadbalancer.server.port: "8180"


  - name: "Success Notification"
    debug:
        msg: "Traefik is now accessible at http://{{ ansible_hostname }}.local:{{ traefik_ui_port | string }}"
