---
# tasks file for roles/traefik

  - name: Ensures /container_data/traefik_config exists, creates it if not
    ansible.builtin.file:
        group: docker
        mode: 0755
        owner: ansible
        state: directory
        path: "{{ local_config_path }}"

  - name: "Create traefik.yaml in {{ local_config_path }} from template"
    template: 
        src: traefik.yaml.j2
        dest: "{{ local_config_path }}/traefik.yaml"
    notify: Restart traefik container


  - name: "Deploy traefik container"
    docker_container:
        name: traefik
        hostname: traefik
        image: traefik
        restart_policy: unless-stopped
        state: started
        ports: 
          - "{{ traefik_ui_port }}:8080"
          - 80:80
          - 443:443
        mounts:
          - source: "{{ local_config_path }}"
            target: /etc/traefik/
            read_only: no
            type: bind
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            read_only: no
            type: bind
        env:
          TZ: "America/Los_Angeles"
          PUID: "1001"
          PGID: "997"
        comparisons:        
            env: strict

  - name: "Success Notification"
    debug:
        msg: "Traefik is now accessible at http://{{ ansible_hostname }}.local:{{ traefik_ui_port | string }}"
