# tasks file for plex
---

  - name: Add Nvidia's official GPG key
    apt_key:
      url: https://nvidia.github.io/nvidia-docker/gpgkey
      state: present

  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: C95B321B61E88C180F759DDCAE044F796ECB0
      state: present
      
  - name: Debug URL used below
    debug: 
        msg: "{{ nvidia_repos }}"

  - name: Add Nvidia repository into sources list using "nvidia-docker.list" as filename
    apt_repository:
        repo: "{{ item }}"
        state: present
        filename: nvidia-docker
    with_items: "{{ nvidia_repos }}"
    when: item is match("deb\s.*")
     
  - name: Install nvidia's container toolkit
    apt:
        name:             
            #- nvidia-container-runtime
            - nvidia-docker2
        state: present
        install_recommends: yes
        update_cache: yes
    notify: Restart docker service

        
  - name: "Create Plex Required Directories"
    ansible.builtin.file:
        state: directory
        dest: "{{ item }}"
    loop:
        - /snoqualmie/media
        - /seatac/plex/config
        - /seatac/plex/transcode
        - /seatac/plex/backups
        - /seatac/plex/certs


  - name: Debug Traefik labels dictionary
    debug: var=traefik_labels
    
  - name: "Deploy {{ app_name }} container"
    docker_container:
        name: plex
        hostname: plex
        image: plexinc/pms-docker:plexpass
        restart_policy: unless-stopped
        state: started
        network_mode: host
        mounts:
          - source: /snoqualmie/media
            target: /media
            read_only: no
            type: bind

          - source: /seatac/plex/config
            target: /config
            read_only: no
            type: bind
            
          - source: /seatac/plex/transcode
            target: /transcode
            read_only: no
            type: bind

          - source: /seatac/plex/backups
            target: /data/backups
            read_only: no
            type: bind

          - source: /seatac/plex/certs
            target: /data/certs
            read_only: no
            type: bind        
        device_requests: 
          - device_ids: '0'
            driver: nvidia
            
            capabilities: 
              - gpu
              - compute
              - video
              - utility
        env:
            TZ: "America/Los_Angeles"
            PUID: "1001"
            PGID: "997"
            PLEX_UID: "1001"
            PLEX_GID: "997"
            PLEX_CLAIM: "claim-ey8YSWwhmmp6mo7oTaMH"
            ADVERTISE_IP: "{{ ansible_default_ipv4.address }}"
        comparisons:        
            env: strict
        
            
            
  - name: Success message
    debug: 
        msg: "Plex should be accessible locally at http://{{ ansible_hostname }}.local:{{ plex_ui_port | string }}/web/"