---
-   hosts: main

    vars_prompt:  
        
      - name: workers_list
        prompt: "List workers to be rebooted (No commas, eg. p1 p2 p4)"
        default: "p1 p2 p3 p4"
    
    tasks:
      - name: power down. `workers_list` including {{ workers_list }}
        command: /sbin/clusterctrl off {{ workers_list}}
        tags:
            - clusterctrl_off

      - name: chill for a bit 
        command: sleep 10        
            
      - name: power up worker pis {{ workers_list }}
        command: /sbin/clusterctrl on {{ workers_list }}
        tags: 
            - clusterctrl_on
            
    