# This is modified from a playbook by Aruna Lakmal
# https://www.techcrumble.net/2019/12/how-install-docker-and-docker-compose-using-ansible-playbooks/

# This playbook requires -K (--ask-become-pass) because the remote user must become root 
# to lock apt (most apt functions require sudo), if your remote_user does not have NOPASSWD powers

--- 
  - hosts: main
    become: yes
    remote_user: ansible



# User that Ansible runs as on the remote system can be passed or defined below.

    tasks:


      - name: Install docker prerequisites and iptables-persistent
        apt:
            name: 
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - iptables-persistent
            state: present
            update_cache: yes
        tags:
          - docker
          - controller
          - workers

      - name: Add Docker's official GPG key
        apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present
        tags:
          - docker
          - controller
          - workers
          
      - name: Verify that we have the key with the fingerprint
        apt_key:
          id: 0EBFCD88
          state: present
        tags:
          - docker
          - controller
          - workers

      - name: Set up the stable repository
        apt_repository:
          repo: deb [arch=armhf] https://download.docker.com/linux/debian/ buster stable
          state: present
          update_cache: yes
        tags:
          - docker
          - controller
          - workers

      - name: Install docker
        apt:
          name: 
            - docker-ce
            - docker-ce-cli
          state: present
          update_cache: yes
        #notify: Start docker on boot
                    
      - name: "Add remote-user to 'docker' group"
        user:
          name: "{{ ansible_uname }}"
          group: "docker"
          append: yes
          
      - name: "Add remote-user to 'docker' group"
        user:
          name: "{{ interactive_uname }}"
          group: "docker"
          append: yes

      - name: "Remove python-configparser due to incompatibilities with ARM"
        apt:
            name: python-configparser
            state: absent
