# This is modified from a playbook by Aruna Lakmal
# https://www.techcrumble.net/2019/12/how-install-docker-and-docker-compose-using-ansible-playbooks/

# This playbook requires -K (--ask-become-pass) because the remote user must become root 
# to lock apt (most apt functions require sudo), if your remote_user does not have NOPASSWD powers

--- 
  - hosts: main
    become: yes
    remote_user: ansible



# User that Ansible runs as on the remote system can be passed or defined below.

    tasks:


      - debug: var=ansible_user
        tags:
            - groupmod

      - name: Install docker prerequisites and iptables-persistent
        apt:
            name: 
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - iptables-persistent
            state: present
            update_cache: yes
        tags:
          - docker
          - controller
          - workers

      - name: Add Docker's official GPG key
        apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present
        tags:
          - docker
          - controller
          - workers
          
      - name: Verify that we have the key with the fingerprint
        apt_key:
          id: 0EBFCD88
          state: present
        tags:
          - docker
          - controller
          - workers

      - name: Set up the stable repository
        apt_repository:
          repo: deb [arch=armhf] https://download.docker.com/linux/debian/ buster stable
          state: present
          update_cache: yes
        tags:
          - docker
          - controller
          - workers

      - name: Install docker
        apt:
          name: 
            - docker-ce
            - docker-ce-cli
          state: present
          update_cache: yes
        #notify: Start docker on boot
        tags:
          - docker
          - controller
          - workers
                    
      - name: "Add remote-user to 'docker' group"
        user:
          name: "{{ ansible_user }}"
          group: "docker"
          append: yes
        tags:
          - docker
          - groupmod
          - controller
          - workers
          
      - name: "Add remote-user to 'docker' group"
        user:
          name: "jehan"
          group: "docker"
          append: yes
        tags:
          - docker
          - groupmod
          - controller
          - workers

      - name: "Add `iptables` entry to permit reaching clusterhat ZeroWs"
        iptables:
            chain: FORWARD
            policy: ACCEPT
            state: present
        tags:
          - iptables
          - controller
          - workers

      - name: "Add `iptables` entry to permit transit packet on br0 interface"
        iptables:
            chain: FORWARD
            in_interface: br0
            out_interface: br0 
            jump: ACCEPT
            state: present
        tags:
            - controller
      
      - name: "Use iptables-persistent to save modified iptables v4 and v6 to respective files"
        command: 
            cmd: /usr/sbin/iptables-save -f /etc/iptables/rules.v4
        tags:
            - controller
            - workers
            - iptables-save

            
#      - name: Start DHCPd Service, if not already running
#        service: 
#            name: dhcpd.service
#            enabled: yes
#            state: started
#        tags:
#            - dhcpd
#            - controller
    
      - name: "Remove python-configparser due to incompatibilities with ARM"
        apt:
            name: python-configparser
            state: absent
        tags: 
            - controller
            - workers    
            
      - name: Install docker-compose
        apt:
          name: docker-compose
          state: present
          update_cache: yes
        tags:
         - docker_compose
          - controller
          - workers

